#!/usr/bin/env python3
from pymongo import MongoClient
import re

def list_regex_matches(mongo_collection, name_regex):
    regex = re.compile(name_regex, re.IGNORECASE)
    return list(mongo_collection.find({"name": {"$regex": regex}}))

if __name__ == "__main__":
    client = MongoClient('mongodb://127.0.0.1:27017')
    my_db = client.my_db
    school_collection = my_db.school

    documents = list_regex_matches(school_collection, "^Holberton")
    for doc in documents:
        print(doc)
