#!/usr/bin/env python3
from pymongo import MongoClient

if __name__ == "__main__":
    client = MongoClient('mongodb://127.0.0.1:27017')
    my_db = client.my_db
    school_collection = my_db.school
    
    document = { "name": "Holberton school" }
    result = school_collection.insert_one(document)
    print(result.inserted_id)
