#!/usr/bin/env python3
from pymongo import MongoClient

def delete_documents(mongo_collection, name):
    return mongo_collection.delete_many({"name": name})

if __name__ == "__main__":
    client = MongoClient('mongodb://127.0.0.1:27017')
    my_db = client.my_db
    school_collection = my_db.school

    result = delete_documents(school_collection, "Holberton school")
    print(result.deleted_count)
